from typing import Any, Dict, List, Tuple
import torch
from diffusers import ZImagePipeline
import random
import json
from pathlib import Path
from tqdm import tqdm
import time

OUTPUT_DIR = Path("./generated_images")
METADATA_FILE = OUTPUT_DIR / "metadata.jsonl"
BATCH_SIZE = 4
IMAGE_SIZE = 256
NUM_INFERENCE_STEPS = 9

PROMPT_TEMPLATES: Dict[str, List[str]] = {
    "portraits": [
        "a portrait photograph of {subject}",
        "headshot of {subject}, professional lighting",
        "close-up portrait of {subject}, studio lighting",
        "{subject}, portrait photography, 50mm lens",
        "candid portrait of {subject}, natural lighting",
        "environmental portrait of {subject}, lifestyle photography",
        "{subject}, dramatic side lighting, fashion editorial",
        "three-quarter view portrait of {subject}, soft box lighting",
        "{subject}, backlit portrait, golden hour glow",
        "profile portrait of {subject}, minimalist composition",
        "{subject}, beauty portrait, ring light setup",
        "character portrait of {subject}, cinematic lighting",
        "{subject}, corporate headshot, grey background",
        "artistic portrait of {subject}, chiaroscuro lighting",
        "{subject}, outdoor portrait, natural environment",
        "intimate portrait of {subject}, close framing",
        "{subject}, portrait with props, storytelling",
        "group portrait featuring {subject}, social documentary",
        "{subject}, fine art portrait, painterly quality",
        "street portrait of {subject}, urban background",
        "{subject}, glamour portrait, high key lighting",
        "moody portrait of {subject}, low key lighting",
        "{subject}, environmental documentary portrait",
        "editorial portrait of {subject}, magazine quality",
        "{subject}, authentic lifestyle portrait",
    ],
    "landscapes": [
        "a photograph of {scene}",
        "{scene}, landscape photography, golden hour",
        "scenic view of {scene}, wide angle",
        "{scene}, nature photography, high detail",
        "panoramic view of {scene}, sunset lighting",
        "{scene}, dramatic weather conditions, storm approaching",
        "aerial view of {scene}, drone photography",
        "{scene}, blue hour photography, twilight",
        "misty morning at {scene}, atmospheric",
        "{scene}, long exposure, smooth water",
        "winter landscape of {scene}, snow covered",
        "{scene}, spring blossoms, vibrant colors",
        "autumn colors at {scene}, fall foliage",
        "{scene}, starry night sky, astrophotography",
        "sunrise at {scene}, first light",
        "{scene}, dramatic clouds, moody atmosphere",
        "reflection photography at {scene}, mirror lake",
        "{scene}, mountain vista, epic scale",
        "coastal landscape of {scene}, seascape",
        "{scene}, desert photography, arid beauty",
        "tropical landscape of {scene}, lush vegetation",
        "{scene}, alpine meadow, wildflowers",
        "canyon view of {scene}, geological wonder",
        "{scene}, wetlands photography, serene waters",
        "volcanic landscape of {scene}, dramatic terrain",
    ],
    "objects": [
        "product photography of {object}",
        "a photograph of {object} on white background",
        "{object}, studio photography, professional",
        "close-up of {object}, macro photography",
        "{object}, commercial photography, high quality",
        "still life composition featuring {object}",
        "{object}, flat lay photography, overhead view",
        "minimalist product shot of {object}, clean background",
        "{object}, lifestyle product photography, in use",
        "detail shot of {object}, texture focus",
        "{object}, catalog photography, multiple angles",
        "creative composition with {object}, artistic",
        "{object}, e-commerce photography, 360 view",
        "luxury product photography of {object}, premium",
        "{object}, environmental product shot, natural setting",
        "editorial product photography of {object}",
        "{object}, packaging photography, branding visible",
        "action shot of {object}, dynamic composition",
        "{object}, comparison photography, side by side",
        "mood photography featuring {object}, atmospheric",
        "{object}, technical photography, specifications visible",
        "artisan photography of {object}, handcrafted details",
        "{object}, vintage product photography, nostalgic",
        "scale photography of {object}, size reference",
        "{object}, exploded view, component photography",
    ],
    "animals": [
        "a photograph of {animal}",
        "{animal} in natural habitat, wildlife photography",
        "close-up of {animal}, nature documentary style",
        "{animal}, professional wildlife photography",
        "portrait of {animal}, detailed fur/feathers",
        "{animal} in action, behavioral photography",
        "family group of {animal}, social interaction",
        "{animal} hunting, predator behavior",
        "baby {animal}, juvenile wildlife photography",
        "{animal} at sunset, silhouette photography",
        "underwater photograph of {animal}, marine life",
        "{animal} in flight, aerial wildlife photography",
        "macro photography of {animal}, insect detail",
        "{animal} with young, parenting behavior",
        "endangered {animal}, conservation photography",
        "{animal} in winter, snow environment",
        "nocturnal {animal}, night photography",
        "{animal} portrait, eye contact, intimate",
        "herd of {animal}, landscape with wildlife",
        "{animal} feeding, natural behavior",
        "camouflaged {animal}, nature's disguise",
        "{animal} vocalization, communication behavior",
        "playful {animal}, behavioral photography",
        "{animal} migration, mass movement",
        "threatened {animal}, environmental context",
    ],
    "architecture": [
        "architectural photography of {building}",
        "{building}, exterior view, architectural digest style",
        "interior of {building}, wide angle photography",
        "{building}, modern architecture photography",
        "detail shot of {building}, architectural photography",
        "facade of {building}, symmetrical composition",
        "{building} at night, illuminated architecture",
        "aerial view of {building}, urban context",
        "{building}, brutalist architecture, concrete",
        "historic preservation of {building}, heritage",
        "{building} interior design, spatial photography",
        "geometric patterns in {building}, abstract architecture",
        "{building}, sustainable architecture, green design",
        "construction photography of {building}, progress",
        "{building} reflection, glass and steel",
        "minimalist architecture of {building}, clean lines",
        "{building}, gothic architecture, ornate details",
        "public space in {building}, human scale",
        "{building} roofscape, urban photography",
        "industrial architecture of {building}, functional design",
        "{building}, religious architecture, sacred space",
        "residential architecture of {building}, living spaces",
        "{building} staircase, architectural feature",
        "urban decay of {building}, abandoned architecture",
        "{building}, parametric architecture, computational design",
    ],
    "food": [
        "food photography of {dish}",
        "{dish}, overhead view, professional food styling",
        "close-up of {dish}, gourmet presentation",
        "{dish}, restaurant quality, appetizing",
        "artful presentation of {dish}, culinary photography",
        "{dish} being prepared, cooking process",
        "rustic food photography of {dish}, natural setting",
        "{dish}, fine dining presentation, elegant",
        "action shot of {dish}, pouring or cutting",
        "{dish}, ingredients layout, deconstructed",
        "street food photography of {dish}, authentic",
        "{dish}, dessert photography, indulgent",
        "farm to table {dish}, organic ingredients",
        "{dish}, beverage photography, refreshing",
        "comfort food photography of {dish}, homestyle",
        "{dish}, vegan presentation, plant-based",
        "molecular gastronomy {dish}, avant-garde",
        "{dish} with steam, hot and fresh",
        "breakfast spread featuring {dish}, morning light",
        "{dish}, cocktail photography, mixology",
        "seasonal {dish}, harvest ingredients",
        "{dish}, baking photography, fresh from oven",
        "sharing platter of {dish}, communal dining",
        "{dish}, healthy meal prep, nutritious",
        "celebratory {dish}, special occasion",
    ],
    "abstract": [
        "abstract art with {concept}",
        "{concept}, abstract expressionism",
        "geometric abstract art featuring {concept}",
        "colorful abstract composition with {concept}",
        "minimalist abstract art, {concept}",
        "{concept}, fluid abstract art, organic forms",
        "digital abstract art, {concept}, modern",
        "{concept}, abstract photography, experimental",
        "textured abstract with {concept}, tactile",
        "{concept}, color field painting style",
        "abstract macro of {concept}, close detail",
        "{concept}, kinetic abstract art, movement",
        "layered abstract featuring {concept}, depth",
        "{concept}, monochromatic abstract, tonal",
        "splatter art with {concept}, action painting",
        "{concept}, constructivist abstract, structured",
        "ethereal abstract of {concept}, dreamlike",
        "{concept}, hard edge abstract, precise",
        "biomorphic abstract with {concept}, natural forms",
        "{concept}, optical illusion abstract, perceptual",
        "cosmic abstract featuring {concept}, celestial",
        "{concept}, watercolor abstract, flowing",
        "collage abstract with {concept}, mixed media",
        "{concept}, suprematist abstract, geometric",
        "atmospheric abstract of {concept}, ambient",
    ],
    "scenes": [
        "a photograph of {location}",
        "{location}, documentary photography",
        "street photography in {location}",
        "{location}, photojournalism style",
        "everyday life in {location}, candid photography",
        "{location} at rush hour, urban energy",
        "night scene in {location}, city lights",
        "{location}, cultural photography, traditions",
        "dawn in {location}, quiet moments",
        "{location} during festival, celebration photography",
        "rainy day in {location}, atmospheric",
        "{location}, social documentary, human stories",
        "architectural context of {location}, built environment",
        "{location} market scene, commerce and culture",
        "public transportation in {location}, commuter life",
        "{location}, neighborhood photography, community",
        "winter scene in {location}, seasonal atmosphere",
        "{location} from above, urban planning perspective",
        "nightlife in {location}, entertainment district",
        "{location}, industrial zone, working landscapes",
        "historic district of {location}, preservation",
        "{location} waterfront, maritime atmosphere",
        "suburban scene in {location}, residential life",
        "{location}, protest or gathering, social movement",
        "changing seasons in {location}, temporal documentation",
    ],
    "fashion": [
        "fashion photography of {subject}",
        "{subject}, haute couture editorial",
        "runway photograph of {subject}, fashion week",
        "{subject}, street style photography, urban fashion",
        "avant-garde fashion with {subject}, conceptual",
        "{subject}, minimalist fashion editorial, clean",
        "luxury fashion photography of {subject}, high-end",
        "{subject}, sustainable fashion, eco-conscious",
        "vintage fashion styling of {subject}, retro",
        "{subject}, athleisure photography, active wear",
        "bohemian fashion with {subject}, free-spirited",
        "{subject}, formal wear photography, elegant",
        "experimental fashion featuring {subject}, artistic",
        "{subject}, accessories photography, detail focus",
        "knitwear photography of {subject}, textural",
        "{subject}, swimwear editorial, summer fashion",
        "outerwear photography of {subject}, seasonal",
        "{subject}, footwear photography, shoe focus",
        "editorial fashion with {subject}, magazine quality",
        "{subject}, denim photography, casual style",
        "gender-fluid fashion with {subject}, inclusive",
        "{subject}, plus-size fashion, body positive",
        "cultural fashion of {subject}, traditional dress",
        "{subject}, festival fashion, bold and creative",
        "business fashion with {subject}, professional style",
    ],
    "sports": [
        "action sports photograph of {athlete}",
        "{athlete}, peak performance moment, decisive instant",
        "team sports photography featuring {athlete}",
        "{athlete}, extreme sports, adrenaline",
        "athletic portrait of {athlete}, determination",
        "{athlete} in motion, motion blur technique",
        "underwater sports photography of {athlete}",
        "{athlete}, victory moment, celebration",
        "training photograph of {athlete}, preparation",
        "{athlete}, aerial sports photography, from above",
        "contact sports moment with {athlete}, intensity",
        "{athlete}, precision sports, concentration",
        "endurance sports photography of {athlete}",
        "{athlete}, winter sports, snow action",
        "skateboarding photography of {athlete}, street sports",
        "{athlete}, gymnastics photography, grace and power",
        "martial arts photograph of {athlete}, technique",
        "{athlete}, motorsports photography, speed",
        "climbing photography of {athlete}, vertical challenge",
        "{athlete}, surfing photography, wave action",
        "athletic fashion of {athlete}, sportswear",
        "{athlete}, paralympic sports, adaptive athletics",
        "youth sports photography with {athlete}",
        "{athlete}, fitness photography, strength training",
        "professional sports moment of {athlete}, career defining",
    ],
    "nature": [
        "nature photography of {element}",
        "{element}, macro nature, tiny worlds",
        "botanical photography of {element}, plant detail",
        "{element}, geological formation, earth science",
        "ecosystem photograph featuring {element}",
        "{element}, seasonal change, nature's cycles",
        "conservation photography of {element}, environmental",
        "{element}, fungal photography, forest floor",
        "water photography of {element}, aquatic",
        "{element}, lichens and moss, micro habitats",
        "tree portrait of {element}, arboreal",
        "{element}, coral reef photography, underwater",
        "meadow photography featuring {element}, grassland",
        "{element}, rock formation, geological time",
        "wetland photography of {element}, marsh ecosystem",
        "{element}, alpine environment, high altitude",
        "desert flora and {element}, arid adaptation",
        "{element}, rainforest canopy, tropical",
        "tide pool photography of {element}, intertidal",
        "{element}, cave photography, underground",
        "prairie landscape with {element}, open plains",
        "{element}, volcanic geology, formation",
        "bog photography featuring {element}, acidic wetland",
        "{element}, tundra landscape, arctic",
        "river system with {element}, freshwater",
    ],
    "urban": [
        "urban photography of {subject}",
        "{subject}, city skyline, metropolitan",
        "infrastructure photograph of {subject}",
        "{subject}, graffiti art, street culture",
        "urban decay featuring {subject}, abandonment",
        "{subject}, gentrification photography, change",
        "public art installation of {subject}",
        "{subject}, urban wildlife, nature in cities",
        "transportation hub with {subject}, mobility",
        "{subject}, rooftop photography, elevated view",
        "alleyway scene featuring {subject}, back streets",
        "{subject}, urban renewal, development",
        "neon signs and {subject}, nightlife",
        "{subject}, construction site, building cities",
        "urban gardens with {subject}, green spaces",
        "{subject}, pedestrian zones, walkability",
        "underground spaces featuring {subject}, subway",
        "{subject}, urban density, population",
        "mixed-use development with {subject}, planning",
        "{subject}, smart city technology, innovation",
        "heritage buildings and {subject}, preservation",
        "{subject}, urban poverty, inequality",
        "public square featuring {subject}, gathering place",
        "{subject}, vertical city, high-rise living",
        "sustainable urbanism with {subject}, eco-city",
    ],
    "events": [
        "event photography of {occasion}",
        "{occasion}, wedding photography, ceremony",
        "concert photograph of {occasion}, live music",
        "{occasion}, corporate event, professional",
        "festival photography featuring {occasion}",
        "{occasion}, birthday celebration, party",
        "graduation ceremony of {occasion}, milestone",
        "{occasion}, conference photography, business",
        "theatrical performance of {occasion}, stage",
        "{occasion}, sporting event, competition",
        "cultural ceremony featuring {occasion}",
        "{occasion}, protest march, activism",
        "awards ceremony of {occasion}, recognition",
        "{occasion}, exhibition opening, art event",
        "parade photography featuring {occasion}",
        "{occasion}, religious ceremony, spiritual",
        "charity gala of {occasion}, fundraising",
        "{occasion}, product launch event, unveiling",
        "memorial service for {occasion}, remembrance",
        "{occasion}, fashion show, runway event",
        "political rally featuring {occasion}",
        "{occasion}, trade show, industry event",
        "community gathering of {occasion}, local",
        "{occasion}, virtual event, hybrid format",
        "anniversary celebration of {occasion}, milestone",
    ],
}

PROMPT_SUBJECTS: Dict[str, List[str]] = {
    "portraits": [
        "a young woman",
        "an elderly man",
        "a child",
        "a teenager",
        "a business professional",
        "an artist",
        "a scientist",
        "an athlete",
        "a person wearing glasses",
        "someone smiling",
        "a serious expression",
        "a person with curly hair",
        "someone in traditional clothing",
        "a musician",
        "a chef",
        "a dancer",
        "a student",
        "a parent with child",
        "someone laughing",
        "a person in meditation",
        "an entrepreneur",
        "a teacher",
        "someone with tattoos",
        "a person in uniform",
        "twins",
        "a bearded man",
        "someone with dreadlocks",
        "a person in sunglasses",
        "an expectant mother",
        "a graduate",
        "someone crying",
        "a person with freckles",
        "a model",
        "someone in costume",
        "a person with long hair",
        "an elder with wisdom lines",
        "someone in profile",
        "a person wearing a hat",
        "identical siblings",
        "someone with piercing eyes",
        "a person mid-laugh",
        "someone contemplating",
        "a person with distinctive features",
        "someone in theatrical makeup",
        "a person at work",
        "someone exercising",
        "a person reading",
        "someone cooking",
        "a person dancing",
        "someone painting",
        "a person writing",
        "someone meditating",
        "a person embracing another",
        "someone looking away",
        "a person in motion",
        "someone resting",
        "a person celebrating",
        "someone determined",
        "a person vulnerable",
        "someone confident",
        "a person curious",
        "someone peaceful",
        "a person joyful",
        "someone thoughtful",
        "a person strong",
    ],
    "landscapes": [
        "mountains at sunset",
        "a forest in autumn",
        "a beach at sunrise",
        "desert sand dunes",
        "a waterfall",
        "snowy peaks",
        "rolling hills",
        "a lake surrounded by trees",
        "dramatic clouds over plains",
        "coastal cliffs",
        "a valley",
        "misty mountains",
        "volcanic crater",
        "canyon walls",
        "alpine meadow",
        "rocky shoreline",
        "river delta",
        "ice fields",
        "limestone karsts",
        "prairie grasslands",
        "fjord waters",
        "sand dunes at dusk",
        "terraced rice fields",
        "slot canyon",
        "tidal flats",
        "mountain lake",
        "redwood forest",
        "badlands formations",
        "coral reef shallows",
        "moss-covered rocks",
        "pine forest",
        "wildflower field",
        "eroded sandstone",
        "mangrove swamp",
        "basalt columns",
        "glacier valley",
        "hot springs",
        "limestone caves",
        "tundra landscape",
        "salt flats",
        "rainbow over valley",
        "lighthouse on cliff",
        "windswept coast",
        "geyser field",
        "jungle canopy",
        "savanna at golden hour",
        "northern lights over mountains",
        "cherry blossoms",
        "bamboo forest",
        "lavender fields",
        "olive groves",
        "vineyard rows",
        "tulip fields",
        "sunflower meadow",
        "tea plantations",
        "lighthouse at storm",
        "castle on hill",
        "bridge over gorge",
        "mesa landscape",
        "oasis in desert",
        "frozen waterfall",
        "double rainbow",
        "meteor shower",
        "solar eclipse",
        "blood moon",
    ],
    "objects": [
        "a coffee cup",
        "a vintage camera",
        "a smartphone",
        "a book",
        "a watch",
        "headphones",
        "a plant",
        "a chair",
        "a lamp",
        "sunglasses",
        "a keyboard",
        "a pen",
        "shoes",
        "a backpack",
        "a bicycle",
        "a guitar",
        "a wine bottle",
        "a vinyl record",
        "a telescope",
        "a compass",
        "a typewriter",
        "a globe",
        "a microscope",
        "paintbrushes",
        "a fountain pen",
        "a pocket watch",
        "a leather journal",
        "a tea set",
        "chess pieces",
        "a vase",
        "candles",
        "crystals",
        "seashells",
        "vintage postcards",
        "antique keys",
        "a sextant",
        "binoculars",
        "a briefcase",
        "a wallet",
        "jewelry",
        "a perfume bottle",
        "a mirror",
        "scissors",
        "thread spools",
        "buttons",
        "a thimble",
        "knitting needles",
        "a sewing machine",
        "a toolbox",
        "a hammer",
        "wrenches",
        "measuring tape",
        "a level",
        "sandpaper",
        "paint cans",
        "a skateboard",
        "roller skates",
        "a baseball glove",
        "a basketball",
        "dumbbells",
        "yoga mat",
        "running shoes",
        "a trophy",
        "medals",
    ],
    "animals": [
        "a cat",
        "a dog",
        "a bird",
        "a lion",
        "an elephant",
        "a fox",
        "a bear",
        "a deer",
        "a tiger",
        "a wolf",
        "an owl",
        "a horse",
        "a rabbit",
        "a squirrel",
        "a butterfly",
        "a dolphin",
        "a whale",
        "a shark",
        "a sea turtle",
        "a penguin",
        "an eagle",
        "a hawk",
        "a hummingbird",
        "a peacock",
        "a flamingo",
        "a parrot",
        "a crow",
        "a swan",
        "a duck",
        "a heron",
        "a pelican",
        "a puffin",
        "a kingfisher",
        "an ostrich",
        "a cheetah",
        "a leopard",
        "a jaguar",
        "a panther",
        "a lynx",
        "a puma",
        "a hyena",
        "a zebra",
        "a giraffe",
        "a rhinoceros",
        "a hippopotamus",
        "a gorilla",
        "a chimpanzee",
        "an orangutan",
        "a lemur",
        "a sloth",
        "a kangaroo",
        "a koala",
        "a panda",
        "a red panda",
        "a raccoon",
        "an otter",
        "a beaver",
        "a hedgehog",
        "a porcupine",
        "a meerkat",
        "a prairie dog",
        "a chipmunk",
        "a ferret",
        "a weasel",
    ],
    "architecture": [
        "a modern skyscraper",
        "a historic cathedral",
        "a cozy cottage",
        "a minimalist house",
        "an art deco building",
        "a glass office building",
        "a brick warehouse",
        "a wooden cabin",
        "a concrete structure",
        "a contemporary museum",
        "a traditional temple",
        "a stone castle",
        "a Victorian mansion",
        "a brutalist complex",
        "a geodesic dome",
        "a lighthouse",
        "a bridge",
        "a train station",
        "an airport terminal",
        "a shopping mall",
        "a sports stadium",
        "a concert hall",
        "a library",
        "a courthouse",
        "a city hall",
        "a hospital",
        "a school building",
        "a university campus",
        "a factory",
        "a windmill",
        "a water tower",
        "a barn",
        "a silo",
        "a greenhouse",
        "a pagoda",
        "a mosque",
        "a synagogue",
        "a monastery",
        "a palace",
        "a fortress",
        "ruins",
        "a colonnade",
        "an amphitheater",
        "a pavilion",
        "a gazebo",
        "a pergola",
        "a treehouse",
        "a houseboat",
        "an igloo",
        "a yurt",
        "a pyramid",
        "a ziggurat",
        "a mausoleum",
        "an observatory",
        "a planetarium",
        "a fire station",
        "a police station",
        "a prison",
        "a bunker",
        "a tower",
        "a minaret",
        "a bell tower",
        "a clock tower",
        "a chimney",
    ],
    "food": [
        "a gourmet burger",
        "sushi platter",
        "pasta carbonara",
        "chocolate cake",
        "fresh salad",
        "grilled steak",
        "pizza",
        "ramen bowl",
        "fruit tart",
        "breakfast plate",
        "tacos",
        "ice cream sundae",
        "seafood platter",
        "vegetable curry",
        "lobster",
        "oysters",
        "caviar",
        "cheese board",
        "charcuterie",
        "bruschetta",
        "caprese salad",
        "risotto",
        "lasagna",
        "ravioli",
        "gnocchi",
        "paella",
        "pad thai",
        "pho",
        "dim sum",
        "dumplings",
        "spring rolls",
        "tempura",
        "sashimi",
        "bibimbap",
        "bulgogi",
        "falafel",
        "hummus",
        "shawarma",
        "kebab",
        "biryani",
        "tandoori chicken",
        "butter chicken",
        "naan bread",
        "samosa",
        "croissant",
        "macarons",
        "crème brûlée",
        "tiramisu",
        "panna cotta",
        "cheesecake",
        "brownies",
        "cookies",
        "donuts",
        "cupcakes",
        "soufflé",
        "mousse",
        "gelato",
        "sorbet",
        "churros",
        "baklava",
        "strudel",
        "pavlova",
        "trifle",
    ],
    "abstract": [
        "swirling colors",
        "geometric shapes",
        "flowing lines",
        "vibrant gradients",
        "textured patterns",
        "bold contrasts",
        "organic forms",
        "crystalline structures",
        "fluid dynamics",
        "fractal patterns",
        "color blocks",
        "wave patterns",
        "spiral formations",
        "concentric circles",
        "intersecting planes",
        "light refractions",
        "shadow play",
        "motion trails",
        "energy bursts",
        "cosmic swirls",
        "digital glitches",
        "pixelated forms",
        "laser beams",
        "plasma effects",
        "aurora patterns",
        "ink blots",
        "paint splatters",
        "brush strokes",
        "dripping paint",
        "color explosions",
        "smoke wisps",
        "fire patterns",
        "water ripples",
        "ice crystals",
        "sand patterns",
        "wood grain",
        "marble veins",
        "rust textures",
        "metal reflections",
        "glass distortions",
        "prism effects",
        "kaleidoscope views",
        "mirror reflections",
        "double exposures",
        "light leaks",
        "lens flares",
        "bokeh circles",
        "depth layers",
        "perspective lines",
        "vanishing points",
        "tessellations",
        "Penrose tiles",
        "Escher-like patterns",
        "optical illusions",
        "anamorphic art",
        "sacred geometry",
        "mandala patterns",
        "Celtic knots",
        "tribal patterns",
        "Art Nouveau curves",
        "Art Deco lines",
        "Bauhaus forms",
        "Memphis design",
        "Vaporwave aesthetics",
    ],
    "scenes": [
        "a busy city street",
        "a quiet cafe",
        "a park on a sunny day",
        "a train station",
        "a farmers market",
        "an office workspace",
        "a library",
        "a concert venue",
        "a shopping mall",
        "a classroom",
        "a hospital corridor",
        "a subway platform",
        "an airport terminal",
        "a bus stop",
        "a parking garage",
        "a gas station",
        "a laundromat",
        "a barbershop",
        "a tattoo parlor",
        "a bookstore",
        "a record shop",
        "a thrift store",
        "a bakery",
        "a butcher shop",
        "a fish market",
        "a flower shop",
        "a hardware store",
        "a pet store",
        "a gym",
        "a yoga studio",
        "a dance studio",
        "an art gallery",
        "a theater lobby",
        "a movie theater",
        "a bowling alley",
        "an arcade",
        "a pool hall",
        "a bar",
        "a nightclub",
        "a restaurant kitchen",
        "a hotel lobby",
        "a motel",
        "a hostel",
        "a campground",
        "a picnic area",
        "a playground",
        "a skate park",
        "a basketball court",
        "a tennis court",
        "a swimming pool",
        "a beach boardwalk",
        "a pier",
        "a marina",
        "a fishing dock",
        "a construction site",
        "a factory floor",
        "a warehouse",
        "a loading dock",
        "a junkyard",
        "a landfill",
        "a recycling center",
        "a power plant",
    ],
    "fashion": [
        "a model in evening gown",
        "someone in streetwear",
        "a person in business suit",
        "someone wearing activewear",
        "a model in swimwear",
        "someone in vintage clothing",
        "a person in bohemian style",
        "someone wearing punk fashion",
        "a model in haute couture",
        "someone in minimalist outfit",
        "a person in traditional dress",
        "someone wearing denim",
        "a model in leather jacket",
        "someone in festival attire",
        "a person in winter coat",
        "someone wearing summer dress",
        "a model in designer shoes",
        "someone with luxury handbag",
        "a person in athletic wear",
        "someone wearing jewelry",
        "a model in sunglasses",
        "someone with statement hat",
        "a person in scarf",
        "someone wearing boots",
        "a model in heels",
        "someone in sneakers",
        "a person in formal wear",
        "someone wearing casual outfit",
        "a model in fur coat",
        "someone in trench coat",
        "a person in blazer",
        "someone wearing cardigan",
        "a model in knitwear",
        "someone in silk blouse",
        "a person in linen suit",
        "someone wearing leather pants",
        "a model in pleated skirt",
        "someone in wide-leg trousers",
        "a person in jumpsuit",
        "someone wearing overalls",
        "a model in crop top",
        "someone in turtleneck",
        "a person in hoodie",
        "someone wearing bomber jacket",
        "a model in peacoat",
        "someone in parka",
        "a person in poncho",
        "someone wearing kimono",
        "a model in caftan",
        "someone in sari",
        "a person in hanbok",
        "someone wearing qipao",
        "a model in dirndl",
        "someone in kilt",
        "a person in dashiki",
        "someone wearing abaya",
        "a model in ao dai",
        "someone in folk costume",
        "a person in ceremonial dress",
        "someone wearing religious garb",
        "a model in bridal gown",
        "someone in prom dress",
        "a person in graduation robe",
        "someone wearing scrubs",
    ],
    "sports": [
        "a basketball player",
        "a soccer player",
        "a tennis player",
        "a swimmer",
        "a runner",
        "a cyclist",
        "a gymnast",
        "a skateboarder",
        "a surfer",
        "a snowboarder",
        "a skier",
        "a rock climber",
        "a boxer",
        "a martial artist",
        "a wrestler",
        "a football player",
        "a baseball player",
        "a hockey player",
        "a golfer",
        "a volleyball player",
        "a track athlete",
        "a pole vaulter",
        "a high jumper",
        "a long jumper",
        "a shot putter",
        "a discus thrower",
        "a javelin thrower",
        "a hurdler",
        "a sprinter",
        "a marathoner",
        "a triathlete",
        "a diver",
        "a synchronized swimmer",
        "a water polo player",
        "a rower",
        "a kayaker",
        "a canoeist",
        "a sailor",
        "a windsurfer",
        "a kitesurfer",
        "a bmx rider",
        "a motocross rider",
        "a racing driver",
        "a rally driver",
        "a drag racer",
        "a figure skater",
        "a speed skater",
        "a curler",
        "a bobsledder",
        "a luge athlete",
        "a biathlete",
        "a cross-country skier",
        "a ski jumper",
        "an archer",
        "a fencer",
        "a table tennis player",
        "a badminton player",
        "a squash player",
        "a rugby player",
        "a cricket player",
        "a lacrosse player",
        "a field hockey player",
        "an ultimate frisbee player",
        "a weightlifter",
        "a powerlifter",
    ],
    "nature": [
        "wildflowers",
        "a mushroom",
        "moss and lichen",
        "tree bark",
        "fallen leaves",
        "pine cones",
        "acorns",
        "seed pods",
        "ferns",
        "ivy",
        "vines",
        "roots",
        "branches",
        "tree rings",
        "a bird's nest",
        "spider web",
        "dewdrops",
        "frost patterns",
        "icicles",
        "snowflakes",
        "crystals",
        "geodes",
        "minerals",
        "fossils",
        "shells",
        "coral",
        "seaweed",
        "driftwood",
        "beach glass",
        "pebbles",
        "sand patterns",
        "ripples",
        "waves",
        "tide pools",
        "rock formations",
        "cliffs",
        "caves",
        "stalagmites",
        "stalactites",
        "hot springs",
        "geysers",
        "lava flows",
        "volcanic rock",
        "obsidian",
        "quartz",
        "amethyst",
        "agate",
        "jade",
        "amber",
        "pearls",
        "clouds",
        "fog",
        "mist",
        "rain",
        "lightning",
        "rainbow",
        "sunset colors",
        "stars",
        "moon",
        "planets",
        "meteor",
        "comet",
        "aurora borealis",
    ],
    "urban": [
        "skyscrapers",
        "street lights",
        "traffic",
        "crosswalks",
        "sidewalks",
        "fire escapes",
        "graffiti wall",
        "street art",
        "neon signs",
        "billboards",
        "storefronts",
        "alleyways",
        "manholes",
        "street vendors",
        "bus shelters",
        "bike lanes",
        "parking meters",
        "benches",
        "trash cans",
        "mailboxes",
        "phone booths",
        "subway entrance",
        "tunnels",
        "overpasses",
        "underpasses",
        "bridges",
        "scaffolding",
        "cranes",
        "construction barriers",
        "windows",
        "reflections",
        "shadows",
        "puddles",
        "pigeons",
        "stray cats",
        "street musicians",
        "performers",
        "crowds",
        "rush hour",
        "night lights",
        "fog in streets",
        "snow in city",
        "rain reflections",
        "rooftops",
        "water towers",
        "chimneys",
        "antennas",
        "satellite dishes",
        "air conditioning units",
        "laundry lines",
        "potted plants",
        "urban gardens",
        "community gardens",
        "street trees",
        "parks",
        "playgrounds",
        "fountains",
        "statues",
        "monuments",
        "memorials",
        "murals",
        "mosaics",
    ],
    "events": [
        "a wedding ceremony",
        "a birthday party",
        "a graduation",
        "a concert",
        "a festival",
        "a parade",
        "a protest",
        "a marathon",
        "a sporting event",
        "a conference",
        "a trade show",
        "an exhibition",
        "a gallery opening",
        "a book launch",
        "a film premiere",
        "a fashion show",
        "a awards ceremony",
        "a fundraising gala",
        "a charity event",
        "a political rally",
        "a town hall meeting",
        "a religious ceremony",
        "a baptism",
        "a bar mitzvah",
        "a quinceañera",
        "a baby shower",
        "a bridal shower",
        "an engagement party",
        "an anniversary celebration",
        "a retirement party",
        "a reunion",
        "a memorial service",
        "a funeral",
        "a holiday celebration",
        "a new year's party",
        "a halloween party",
        "a thanksgiving dinner",
        "a christmas gathering",
        "an easter celebration",
        "a diwali festival",
        "a hanukkah celebration",
        "a ramadan iftar",
        "a lunar new year",
        "a carnival",
        "a fair",
        "a rodeo",
        "a circus",
        "a magic show",
        "a comedy show",
        "a theater performance",
        "a dance recital",
        "a music recital",
        "a poetry reading",
        "an open mic night",
        "a trivia night",
        "a game night",
        "a watch party",
        "a tailgate party",
        "a block party",
        "a barbecue",
        "a picnic",
        "a beach party",
    ],
}

STYLE_MODIFIERS: List[str] = [
    "",
    ", dramatic lighting",
    ", soft lighting",
    ", black and white",
    ", vibrant colors",
    ", muted tones",
    ", high contrast",
    ", shallow depth of field",
    ", sharp focus",
    ", cinematic",
    ", photorealistic",
    ", 8k resolution",
    ", professional photography",
    ", golden hour lighting",
    ", blue hour lighting",
    ", natural lighting",
    ", studio lighting",
    ", rim lighting",
    ", backlit",
    ", side lighting",
    ", top lighting",
    ", bottom lighting",
    ", harsh shadows",
    ", soft shadows",
    ", no shadows",
    ", HDR",
    ", long exposure",
    ", fast shutter speed",
    ", motion blur",
    ", bokeh",
    ", lens flare",
    ", vignette",
    ", tilt-shift",
    ", fish-eye lens",
    ", wide angle",
    ", telephoto",
    ", macro",
    ", ultra-wide",
    ", panoramic",
    ", aerial view",
    ", bird's eye view",
    ", worm's eye view",
    ", low angle",
    ", high angle",
    ", dutch angle",
    ", symmetrical composition",
    ", rule of thirds",
    ", leading lines",
    ", frame within frame",
    ", negative space",
    ", patterns and textures",
    ", minimalist",
    ", maximalist",
    ", moody atmosphere",
    ", ethereal",
    ", dreamy",
    ", gritty",
    ", vintage film look",
    ", polaroid style",
    ", sepia tone",
    ", cross-processed",
    ", bleach bypass",
    ", desaturated",
    ", oversaturated",
    ", color graded",
    ", film grain",
    ", clean and crisp",
]

PERSON_DEMOGRAPHICS = [
    "a young adult",
    "a middle-aged person",
    "an elderly person",
    "a teenager",
    "a child",
    "a toddler",
    "someone in their 20s",
    "someone in their 30s",
    "someone in their 40s",
    "someone in their 50s",
    "someone in their 60s",
    "a woman",
    "a man",
    "a person",
    "a non-binary person",
    "an Asian person",
    "a Black person",
    "a Hispanic person",
    "a white person",
    "a person of Indian descent",
    "a Middle Eastern person",
    "a Pacific Islander",
    "a person with dark skin",
    "a person with light skin",
    "a person with olive skin",
]

PERSON_PHYSICAL_FEATURES = [
    "with long straight hair",
    "with short curly hair",
    "with a bald head",
    "with dreadlocks",
    "with braided hair",
    "with a ponytail",
    "with a bun",
    "with shoulder-length hair",
    "with gray hair",
    "with blonde hair",
    "with black hair",
    "with red hair",
    "with brown hair",
    "with blue hair",
    "with an afro",
    "with a mohawk",
    "with wavy hair",
    "with a beard",
    "with a mustache",
    "clean-shaven",
    "with stubble",
    "with glasses",
    "with sunglasses",
    "without glasses",
    "with a wide smile",
    "with a serious expression",
    "laughing",
    "with freckles",
    "with dimples",
    "with high cheekbones",
    "athletic build",
    "slim build",
    "heavyset",
    "muscular",
    "with tattoos",
    "with piercings",
    "with jewelry",
    "wearing a hat",
    "wearing a headscarf",
    "with face paint",
]

PERSON_CLOTHING = [
    "wearing a business suit",
    "in casual clothes",
    "in athletic wear",
    "wearing a dress",
    "in a t-shirt and jeans",
    "in formal attire",
    "wearing a leather jacket",
    "in a hoodie",
    "wearing scrubs",
    "in traditional clothing",
    "wearing a uniform",
    "in winter clothes",
    "wearing a lab coat",
    "in beachwear",
    "wearing vintage clothing",
    "in streetwear",
    "wearing bright colors",
    "in all black",
]

PERSON_ACTIVITIES = [
    "working at a computer",
    "reading a book",
    "drinking coffee",
    "talking on the phone",
    "writing in a notebook",
    "playing guitar",
    "cooking",
    "exercising",
    "meditating",
    "painting",
    "taking a selfie",
    "walking",
    "sitting",
    "standing",
    "looking at the camera",
    "looking away",
    "in motion",
]

PERSON_SETTINGS = [
    "in an office",
    "at home",
    "in a park",
    "on a street",
    "in a cafe",
    "at the beach",
    "in a studio",
    "in a library",
    "at a restaurant",
    "in a gym",
    "outdoors",
    "indoors",
    "against a white background",
    "against a brick wall",
    "in natural surroundings",
    "in an urban environment",
]

LANDSCAPE_TYPES = [
    "mountain range",
    "forest",
    "desert",
    "beach",
    "ocean",
    "lake",
    "river",
    "canyon",
    "valley",
    "plains",
    "hills",
    "waterfall",
    "glacier",
    "volcano",
    "cliff",
    "cave",
    "island",
    "peninsula",
    "meadow",
    "wetlands",
    "tundra",
]

LANDSCAPE_TIME = [
    "at sunrise",
    "at sunset",
    "at golden hour",
    "at noon",
    "at dusk",
    "at dawn",
    "at twilight",
    "under moonlight",
    "on a cloudy day",
    "on a clear day",
    "during storm",
]

LANDSCAPE_SEASON = [
    "in spring",
    "in summer",
    "in autumn",
    "in winter",
    "during cherry blossom season",
    "with fall foliage",
    "covered in snow",
    "in bloom",
    "during monsoon",
]

OBJECTS_DETAILED = {
    "electronics": [
        "a vintage radio",
        "a modern smartphone",
        "a laptop computer",
        "a mechanical keyboard",
        "wireless headphones",
        "a smartwatch",
        "a digital camera",
        "a film camera",
        "a gaming console",
        "a tablet",
        "earbuds",
        "a desktop computer",
        "a CRT monitor",
    ],
    "household": [
        "a ceramic vase",
        "a wooden chair",
        "a metal lamp",
        "a glass bottle",
        "a potted succulent",
        "a cactus",
        "a fern",
        "a decorative bowl",
        "a candle holder",
        "a picture frame",
        "a clock",
        "a mirror",
        "a rug",
    ],
    "food_items": [
        "a fresh apple",
        "a ripe banana",
        "a bunch of grapes",
        "a loaf of bread",
        "a croissant",
        "a donut",
        "a bagel",
        "a slice of pizza",
        "a sandwich",
        "a bowl of soup",
        "a plate of pasta",
        "a steak",
        "a salad",
        "sushi rolls",
    ],
    "tools": [
        "a hammer",
        "a wrench",
        "a screwdriver",
        "pliers",
        "a saw",
        "a drill",
        "a toolbox",
        "a tape measure",
        "scissors",
        "a knife",
        "a chisel",
        "a level",
    ],
    "art_supplies": [
        "a paintbrush",
        "a palette",
        "tubes of paint",
        "a canvas",
        "colored pencils",
        "markers",
        "charcoal",
        "a sketchbook",
        "watercolors",
        "an easel",
    ],
    "sports": [
        "a basketball",
        "a football",
        "a soccer ball",
        "a baseball",
        "a tennis racket",
        "a golf club",
        "a bicycle",
        "roller skates",
        "a skateboard",
        "dumbbells",
        "a yoga mat",
        "running shoes",
    ],
    "fashion": [
        "leather boots",
        "sneakers",
        "high heels",
        "sandals",
        "a handbag",
        "a backpack",
        "a wallet",
        "a belt",
        "a scarf",
        "a hat",
        "gloves",
        "a tie",
        "a watch",
    ],
}


def generate_person_prompt():
    """Generate a highly diverse person portrait prompt"""

    demographic = random.choice(PERSON_DEMOGRAPHICS)

    num_features = random.randint(1, 3)
    features = random.sample(PERSON_PHYSICAL_FEATURES, num_features)
    features_str = ", ".join(features)

    person_desc = f"{demographic} {features_str}"

    if random.random() < 0.5:
        clothing = random.choice(PERSON_CLOTHING)
        person_desc += f", {clothing}"

    if random.random() < 0.4:
        activity = random.choice(PERSON_ACTIVITIES)
        person_desc += f", {activity}"

    if random.random() < 0.6:
        setting = random.choice(PERSON_SETTINGS)
        person_desc += f", {setting}"

    styles = [
        f"portrait photograph of {person_desc}",
        f"professional headshot of {person_desc}",
        f"candid photo of {person_desc}",
        f"studio portrait of {person_desc}",
        f"environmental portrait of {person_desc}",
        f"documentary-style photo of {person_desc}",
    ]

    prompt = random.choice(styles)

    return prompt, "portraits"


def generate_landscape_prompt():
    """Generate diverse landscape prompt"""

    landscape = random.choice(LANDSCAPE_TYPES)
    time = random.choice(LANDSCAPE_TIME)

    if random.random() < 0.5:
        season = random.choice(LANDSCAPE_SEASON)
        prompt = f"landscape photography of {landscape} {season} {time}"
    else:
        prompt = f"landscape photography of {landscape} {time}"

    weather = [
        ", misty atmosphere",
        ", dramatic clouds",
        ", clear sky",
        ", fog rolling in",
        ", rays of light",
        ", storm approaching",
        ", rainbow visible",
        ", partly cloudy",
        "",
        "",
    ]

    if random.random() < 0.4:
        prompt += random.choice(weather)

    return prompt, "landscapes"


def generate_object_prompt():
    """Generate diverse object prompt"""

    category = random.choice(list(OBJECTS_DETAILED.keys()))
    obj = random.choice(OBJECTS_DETAILED[category])

    styles = [
        f"product photography of {obj}, white background",
        f"close-up photo of {obj}, macro lens",
        f"still life photography featuring {obj}",
        f"studio photo of {obj}, professional lighting",
        f"overhead view of {obj}, flat lay style",
        f"artistic photo of {obj}, dramatic lighting",
        f"{obj} on a wooden table",
        f"{obj} in natural setting",
    ]

    prompt = random.choice(styles)

    return prompt, "objects"


def generate_animal_prompt():
    """Generate diverse animal prompt"""

    animals = [
        "a tabby cat",
        "a siamese cat",
        "a persian cat",
        "a maine coon cat",
        "a golden retriever",
        "a german shepherd",
        "a bulldog",
        "a poodle",
        "a husky",
        "a corgi",
        "a chihuahua",
        "a dalmatian",
        "an eagle",
        "a parrot",
        "a owl",
        "a hummingbird",
        "a peacock",
        "a penguin",
        "a flamingo",
        "a crow",
        "a swan",
        "a lion",
        "a tiger",
        "a leopard",
        "a cheetah",
        "an elephant",
        "a giraffe",
        "a zebra",
        "a rhinoceros",
        "a bear",
        "a wolf",
        "a fox",
        "a deer",
        "a moose",
        "a dolphin",
        "a whale",
        "a seal",
        "a sea turtle",
        "a frog",
        "a lizard",
        "a snake",
        "a butterfly",
        "a dragonfly",
    ]

    animal = random.choice(animals)

    settings = [
        f"wildlife photography of {animal} in natural habitat",
        f"close-up portrait of {animal}",
        f"{animal}, nature documentary style",
        f"{animal} in action, motion captured",
        f"detailed photo of {animal}, National Geographic style",
        f"{animal}, professional wildlife photography",
    ]

    prompt = random.choice(settings)

    return prompt, "animals"


def generate_random_prompt() -> Tuple[str, str]:
    try:
        categories_with_generators = [
            (generate_person_prompt, 0.30),
            (generate_landscape_prompt, 0.20),
            (generate_object_prompt, 0.20),
            (generate_animal_prompt, 0.15),
        ]

        use_old_style = random.random() < 0.15

        if use_old_style:
            category = random.choice(["architecture", "food", "abstract", "scenes"])

            if category not in PROMPT_TEMPLATES or category not in PROMPT_SUBJECTS:
                prompt, cat = generate_landscape_prompt()
                return prompt, cat

            template = random.choice(PROMPT_TEMPLATES[category])
            subject = random.choice(PROMPT_SUBJECTS[category])

            prompt = template.format(
                building=subject,
                dish=subject,
                concept=subject,
                location=subject,
            )

            if random.random() < 0.3:
                prompt += random.choice(STYLE_MODIFIERS)

            return prompt, category
        else:
            generators = [g for g, _ in categories_with_generators]
            weights = [w for _, w in categories_with_generators]
            generator = random.choices(generators, weights=weights)[0]

            prompt, category = generator()

            if random.random() < 0.2:
                prompt += random.choice(STYLE_MODIFIERS)

            return prompt, category

    except Exception as e:
        print(f"Error in generate_random_prompt: {e}")
        traceback.print_exc()
        return "a photograph of a landscape", "landscapes"


def generate_params() -> Dict[str, Any]:
    return {
        "num_inference_steps": random.choice([7, 8, 9, 10]),
        "height": random.choice([768, 512, 256]),
        "width": random.choice([768, 512, 256]),
        "seed": random.randint(0, 2**32 - 1),
    }


def generate_dataset(num_images: int):
    print("Loading Z-Image pipeline...")
    pipe = ZImagePipeline.from_pretrained(
        "Tongyi-MAI/Z-Image-Turbo",
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=False,
    )
    pipe.to("cuda")

    print(f"Starting output of {num_images} images...")
    print(f"Output directory: {OUTPUT_DIR}")

    generation_times: List[float] = []
    category_counts: Dict[str, int] = {}

    with open(METADATA_FILE, "w") as meta_file:
        for i in tqdm(range(num_images), desc="Generating images"):
            try:
                prompt, category = generate_random_prompt()
                params = generate_params()

                category_counts[category] = category_counts.get(category, 0) + 1

                start_time = time.time()

                image = pipe(
                    prompt=prompt,
                    height=params["height"],
                    width=params["width"],
                    num_inference_steps=params["num_inference_steps"],
                    guidance_scale=0.0,
                    generator=torch.Generator("cuda").manual_seed(params["seed"]),
                ).images[0]

                generation_time = time.time() - start_time
                generation_times.append(generation_time)

                image_filename = f"image_{i:06d}.png"
                image_path = OUTPUT_DIR / image_filename
                image.save(image_path)

                metadata = {
                    "image_id": i,
                    "filename": image_filename,
                    "prompt": prompt,
                    "category": category,
                    "seed": params["seed"],
                    "height": params["height"],
                    "width": params["width"],
                    "num_inference_steps": params["num_inference_steps"],
                    "generation_time": generation_time,
                }
                meta_file.write(json.dumps(metadata) + "\n")
                meta_file.flush()

                if (i + 1) % 10 == 0:
                    avg_time = sum(generation_times[-10:]) / len(generation_times[-10:])
                    remaining = num_images - (i + 1)
                    eta_seconds = remaining * avg_time
                    eta_hours = eta_seconds / 3600

                    print("\n--- Progress Update ---")
                    print(f"Generated: {i + 1}/{num_images}")
                    print(f"Avg time per image: {avg_time:.2f}s")
                    print(f"ETA: {eta_hours:.2f} hours")
                    print(f"Category distribution: {category_counts}")

            except Exception as e:
                print(f"\nError generating image {i}: {e}")
                continue

    print("\n" + "=" * 50)
    print("GENERATION COMPLETE!")
    print("=" * 50)
    print(f"Total images: {num_images}")
    print(
        f"Average generation time: {sum(generation_times) / len(generation_times):.2f}s"
    )
    print(f"Total time: {sum(generation_times) / 3600:.2f} hours")
    print("\nCategory distribution:")
    for category, count in sorted(category_counts.items()):
        print(f"  {category}: {count} ({100 * count / num_images:.1f}%)")
    print(f"\nImages saved to: {OUTPUT_DIR}")
    print(f"Metadata saved to: {METADATA_FILE}")


def count_existing_images():
    """Count how many images already exist"""
    if not OUTPUT_DIR.exists():
        return 0
    return len(list(OUTPUT_DIR.glob("image_*.png")))


def resume_generation():
    """Resume generation if interrupted"""
    existing = count_existing_images()
    if existing > 0:
        response = input(
            f"Found {existing} existing images. Resume from there? (y/n): "
        )
        if response.lower() == "y":
            return existing
    return 0


def main():
    start_idx = resume_generation()

    OUTPUT_DIR.mkdir(exist_ok=True)
    METADATA_FILE.touch(exist_ok=True)

    num_images = 50_000

    if start_idx > 0:
        print(f"Resuming from image {start_idx}")
        num_images = num_images - start_idx

    generate_dataset(num_images)


if __name__ == "__main__":
    main()
